spring:
  application:
    name: tdebt

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME}?currentSchema=${CURRENT_DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 25
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: tdebtapp
    default-schema: tdebtapp

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}

  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

  allowed:
    origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}