-- ============================================================
-- ROLES & CAPABILITIES
-- ============================================================
CREATE TABLE roles (
    id           BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)    NOT NULL,

    CONSTRAINT   pk_roles        PRIMARY KEY (id),
    CONSTRAINT   uk_roles_name   UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles (name);


CREATE TABLE capabilities (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(255)    NULL,

    CONSTRAINT  pk_capabilities      PRIMARY KEY (id),
    CONSTRAINT  uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities (name);


CREATE TABLE roles_capabilities (
    role_id       BIGINT        NOT NULL,
    capability_id BIGINT        NOT NULL,

    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability
        FOREIGN KEY (capability_id) REFERENCES capabilities (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);


-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE users (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID            NOT NULL,
    email       VARCHAR(255)    NOT NULL,
    password    VARCHAR(255)    NOT NULL,
    role_id     BIGINT          NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL,
    updated_at  TIMESTAMPTZ     NOT NULL,
    deleted     BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ     NULL,

    CONSTRAINT pk_users             PRIMARY KEY (id),
    CONSTRAINT uk_users_uuid        UNIQUE (uuid),
    CONSTRAINT uk_users_email       UNIQUE (email),
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_users_email    ON users (email);
CREATE INDEX ix_users_role_id   ON users (role_id);
CREATE INDEX ix_users_deleted   ON users (deleted) WHERE deleted = false;


-- ============================================================
-- DEBTS
-- ============================================================
CREATE TABLE debts (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID            NOT NULL,
    debtor_name VARCHAR(50)     NOT NULL,
    debt_type   VARCHAR(50)     NOT NULL
        CHECK (debt_type IN ('I_OWE', 'OWED_TO_ME')),
    balance     NUMERIC(19, 4)  NOT NULL DEFAULT 0,
    description VARCHAR(255),
    debt_status VARCHAR(50)     NOT NULL DEFAULT 'OPEN'
        CHECK (debt_status IN ('OPEN', 'SETTLED', 'CANCELLED')),
    user_id     BIGINT          NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL,
    updated_at  TIMESTAMPTZ     NOT NULL,
    deleted     BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT  pk_debts        PRIMARY KEY (id),
    CONSTRAINT  uk_debts_uuid   UNIQUE (uuid),
    CONSTRAINT  fk_debts_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_debts_type ON debts (debt_type) WHERE deleted = false;
CREATE INDEX ix_debts_deleted ON debts (deleted) WHERE deleted = false;
CREATE INDEX ix_debts_user_id ON debts (user_id);
CREATE INDEX idx_debts_user_id_status ON debts (user_id, debt_status) WHERE deleted = false;
CREATE INDEX idx_debts_debtor_name ON debts (debtor_name) WHERE deleted = false;


-- ============================================================
-- TRANSACTIONS (immutable ledger — no soft delete)
-- ============================================================
CREATE TABLE transactions (
    id         BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID            NOT NULL,
    debt_id    BIGINT          NOT NULL,
    date       DATE            NOT NULL,
    amount     NUMERIC(19, 4)  NOT NULL,
    action     VARCHAR(50)     NOT NULL
        CHECK ("action" IN ('INCREASE', 'DECREASE')),
    note       VARCHAR(255),
    created_at TIMESTAMPTZ     NOT NULL,
    updated_at TIMESTAMPTZ     NOT NULL,

    CONSTRAINT  pk_transactions         PRIMARY KEY (id),
    CONSTRAINT  uk_transactions_uuid    UNIQUE (uuid),
    CONSTRAINT  fk_transactions_debt
        FOREIGN KEY (debt_id) REFERENCES debts (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_transactions_debt ON transactions(debt_id);
CREATE INDEX idx_transactions_debt_date ON transactions (debt_id, date);
CREATE INDEX idx_transactions_action ON transactions (action);